name: Deploy React App to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: CI=false npm run build

      - name: Create .htaccess for React SPA (optional)
        run: |
          echo "Options -MultiViews" > build/.htaccess
          echo "RewriteEngine On" >> build/.htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-f" >> build/.htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-d" >> build/.htaccess
          echo "RewriteRule ^ index.html [QSA,L]" >> build/.htaccess

      - name: Upload ONLY build to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./build/
          server-dir: /public_html/       # Domenə uyğun dəyişə bilər
          dangerous-clean-slate: true     # Build zamanı bütün köhnə faylları siləcək
